from src.wave2toa import RxMain

if __name__ == '__main__':
    '''
    parameters definition for rx signal processing ultrasonic sound localization system
    ---------------------------------------------------------------------------------------------
    :param TOA_path - if toa samples already exists: path of the relevant TOA samples. else = ''
    :type string , should br a real path of csv file 
    ---------------------------------------------------------------------------------------------
    :param matlab_path - path of the expected signals that generated by the transmitting unit
    (matlab)
    :type string , should br a real path of mat file with variable 'allchirp'
    ---------------------------------------------------------------------------------------------
    :param record_path
    :type
    ---------------------------------------------------------------------------------------------
    :param speakers_frequencies the recorded chirp frequencies that defined in the Transmitting
    unit. 
    stracture: {'1': [start_freq, stop_freq],'2': [start_freq, stop_freq],...}
    :type  dictionary 
    ---------------------------------------------------------------------------------------------
    :param speakers_locations_d
    stracture: 
    :type
    ---------------------------------------------------------------------------------------------
    :param room_sizes
    :type
    ---------------------------------------------------------------------------------------------
    :param chirp_time
    :type
    ---------------------------------------------------------------------------------------------
    :param filter_size
    :type
    ---------------------------------------------------------------------------------------------
    :param matlab_path
    :type
    ---------------------------------------------------------------------------------------------
    
    
    '''
    params = {}
    algorithm_d = {'chan': 1,
                   'taylor': 2,
                   'room': 3,
                   'both': 4}
    # if TOA already exist
    params['TOA_path'] = ''  # '/Users/roitoledano/git/TDOAchan/TDOAPostProcessing/output/toa_record_1542718040.csv'
    params['speakers_frequencies'] = {'1': [20000, 27000],
                                      '2': [27000, 34000],
                                      '3': [34000, 41000],
                                      '4': [42000, 49000]}
    params['speakers_locations_d'] = {'1': [0.0, 0.0, 2.30],
                                      '2': [3.9, 0.0, 2.25],
                                      '3': [0.65, 3.8, 2.23],
                                      '4': [3.9, 4.04, 1.52]}
    params['room_sizes'] = {'x': 3.9,
                            'y': 4.04,
                            'z': 2.4}

    params['chirp_time'] = 0.002
    params['filter_size'] = 1001
    params['matlab_path'] = '../inputs/chirp_blackman_harris_5ms_Fs500000.mat'
    params['record_path'] = '../inputs/blackmanharris5ms/4.WAV'
    params['signal_mode'] = 1

    params['algorithm'] = algorithm_d['chan']
    params['use_averaging_before_calculation'] = False
    params['time_factor'] = 2
    params['avg_group_size'] = 5
    params['resolution'] = 0.05  # [m]


    RxMain(params)